#!/bin/bash
puppet resource package git ensure=present
puppet resource package apache2 ensure=present
puppet resource service apache2 ensure=running
puppet resource file /script_dir/clone ensure=absent force=true
puppet resource file /script_dir ensure=directory
puppet resource file /script_dir/clone ensure=directory
cd /script_dir/clone
git clone https://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@github.com/lithisha/operate_repo.git
cp -p /script_dir/clone/operate_repo/index.html /var/www/html
	
